### ISSUE TITLE
Why don't we propose a java openjdk 8 s2i image within the community folder ?

### ISSUE THREAD

**Issue by cmoulliard** [openshift/library#135]
Why don't we propose a java openjdk 8 s2i image within the community folder ?

**Comment by bparees** [comment]
build it, maintain it, and submit a PR to have it added.

Or get the team that maintains the rhel openjdk image to do so.

I think a more appropriate place for this request/issue would be against the openjdk image repo itself:
https://github.com/jboss-container-images/redhat-openjdk-18-openshift-image
