### ISSUE TITLE
question about competing templates

### ISSUE THREAD

**Issue by oprudkyi** [openshift/library#15]
I have one template that is very close to MariaDB/MySQL images/templates though more oriented for all-in-one  and corporate setups of OpenShift Origin, i.e. 

 - Uses official images from [MySQL](https://hub.docker.com/r/library/mysql/), [Percona](https://hub.docker.com/r/library/percona/) or 
 [MariaDB](https://hub.docker.com/r/library/mariadb/) repositories
 - Uses local fs on node (hostmount SCC) to store files 
 - Allows to configure my.cnf on creating service from template or later (via ConfigMap)

https://github.com/oprudkyi/openshift-templates/tree/master/hostmount-official-mysql-percona-mariadb

May I add it to the library or it is over-specialized ?

**Comment by bparees** [comment]
it looks pretty specialized, particularly the use of hostpath mounts which is not something normal users have access to use.

**Comment by oprudkyi** [comment]
>it looks pretty specialized, particularly the use of hostpath mounts which is not something normal users have access to use.

I found OpenShift Origin very useful in local setups as replacement for docker-composer (you can just build custom configuration of 'site' just with few mouse clicks)

but yes, this is slightly not what OpenShift was designed for :)
probably there should be separate library for hostmount based templates

**Comment by bparees** [comment]
yeah it sounds like an interesting blog post, but probably not something we'd want the general population of users to try to deploy since it would fail for most of them.
