### ISSUE TITLE
Template for RHPAM74-Authoring: Deploy from BCentral triggers redeploy of kie-server pod

### ISSUE THREAD

**Issue by andremcguire** [openshift/library#195]
Upon upgrading from rhpam73x authoring template to the new rhpam741 authoring template, some critical differences were found.

On 741, using the Deploy function of business central triggers:
[org.kie.server.services.openshift.impl.OpenShiftStartupStrategy] (OkHttp https://172.30.0.1/ ...) KieServer: kieserver-bed9c094-fd97-4dd0-959f-e7b1138b7d95, DC rollout - Begin

This DC rollout is not triggered on 73x.

Issues raised by this:
If using the authoring kie server to rapidly test changes, the user must wait for the new pod to be up and running before committing to a new deploy. Previously it was only required that the kie container be started. Since there is a rolling deployment, the old pod remains active and continues to receive requests (to the new container, while the new pod is starting.)
Problem:
If there is a new container deployment within Business Central (Either via the "Deploy" functionality or via the "Execution Servers" tab) before the new pod is available, that deployment will re-trigger a deployment rollout and the DC of the new pod will not accurately contain the kie container deployment config. This causes the pods to behave erratically often causing a deployment crash loop which can only be resolved by deleting all deployment units and restarting both kie-server and business central pods.
This behaviour makes using the authoring environment very frustrating and time consuming.

**Comment by adambkaplan** [comment]
/close

Issues related to specific templates should be filed against their upstream repositories. I have gone ahead and filed this against the appropriate issue tracker:

https://issues.jboss.org/browse/RHPAM-2499
