### ISSUE TITLE
arch_* tags not respected since golang conversion

### ISSUE THREAD

**Issue by yselkowitz** [openshift/library#226]
Attempting to reverify #225, I ran library-sync.sh in cluster-samples-operator -- first as-is to establish a baseline -- and noticed that all per-arch barriers have completely broken down; P&Z files landed in ocp-x86_64, and x86-only ones in the P&Z directories.  We rely heavily on this functionality in order to keep sane imagestreams for each architecture individually, so it is important that this be fixed.

CC: @gabemontero

**Comment by coreydaley** [comment]
Can you point me to this library-sync.sh script?

**Comment by yselkowitz** [comment]
```
git clone https://github.com/openshift/cluster-samples-operator.git
cd cluster-samples-operator/tmp/build
./library-sync.sh
```

**Comment by gabemontero** [comment]
https://github.com/openshift/cluster-samples-operator/blob/master/tmp/build/library-sync.sh

**Comment by gabemontero** [comment]
@coreydaley when we did the test
- updated the operator folder like the periodic job
- and then I pulled the operator folder from your PRs branch into a test samples operator PR
we were attempting to validate the `library-sync.sh` flow described here

As that effort seemed to have work, either 
- that effort did not fully approximate things,
- or something changes between when we ran that effort and what was finally merged

**Comment by coreydaley** [comment]
Submitted pull request https://github.com/openshift/release/pull/9943 which should fix this.

Probably need to add some tests in the next round of library updates ;)

**Comment by coreydaley** [comment]
Pull request has merged, it should run again within 1-hour and then can you try your script again?

**Comment by yselkowitz** [comment]
No, that's worse, almost everything disappeared:

https://github.com/openshift/library/tree/master/operator/ocp-x86_64/official
