### ISSUE TITLE
Mariadb templates Probe Warning

### ISSUE THREAD

**Issue by strangiato** [openshift/library#275]
The following Maria DB Templates have an incorrectly configured liveness/readiness probe:

- `./official/mariadb/templates/mariadb-ephemeral.json`
- `./official/mariadb/templates/mariadb-persistent.json`

When the probes are executed the following warning is logged in the pod:

```
2021-05-03 20:19:23 29 [Warning] Access denied for user 'userHFP'@'localhost' (using password: YES)
2021-05-03 20:19:27 30 [Warning] Access denied for user 'userHFP'@'localhost' (using password: YES)
2021-05-03 20:19:33 31 [Warning] Access denied for user 'userHFP'@'localhost' (using password: YES)
```

The probe is missing a `;` before the `mysqladmin` command:

```
"command": [
	"/bin/sh",
	"-i",
	"-c",
	"MYSQL_PWD=\"$MYSQL_PASSWORD\"; mysqladmin -u $MYSQL_USER ping"
]
```

**Comment by gabemontero** [comment]
Thanks for the info @strangiato 

They way to fix it per our process is to change the files in https://github.com/sclorg/mariadb-container, working with the maintainers of the SCL mariadb code, and then this repository's background import job will pull those changes in.

Are you willing to open the issue at https://github.com/sclorg/mariadb-container or do you need me to be a proxy for this?

**Comment by strangiato** [comment]
@gabemontero I can open up an issue over there.  Thanks for he heads up on the correct location to get the fix.

I got started on the PR before I saw this so feel free to close out the PR.

**Comment by gabemontero** [comment]
> @gabemontero I can open up an issue over there. Thanks for he heads up on the correct location to get the fix.
> 
> I got started on the PR before I saw this so feel free to close out the PR.

that is what I figured @strangiato no worries

feel free to create a PR in https://github.com/sclorg/mariadb-container as well if you like

**Comment by coreydaley** [comment]
/close
closed in favor of https://github.com/sclorg/mariadb-container/issues/148
