### ISSUE TITLE
Deprecated .NET templates show up in fresh OpenShift sandbox

### ISSUE THREAD

**Issue by tmds** [openshift/library#337]
I've created a free OpenShift Sandbox instance.

I see it includes .NET templates:

![templates](https://user-images.githubusercontent.com/1025424/194056869-fedd9828-6267-438c-b58d-b4c302c5b14e.png)

These templates were removed 2 years ago in https://github.com/openshift/library/pull/250, so I'm surprised they show up in the sandbox.

Is something else needed to remove them from OpenShift?

cc @yselkowitz @gabemontero @bparees @omajid

**Comment by bparees** [comment]
upgrading a cluster doesn't remove content that was already created, so i'm not surprised they are still there, likely being carried forward.  If we truly want them removed from sandbox, someone probably needs to make that request to the sandbox team to delete them from the clusters explicitly.

**Comment by tmds** [comment]
Ah, then they won't be part of fresh installs. That's good.

I'll make a request to the sandbox team.

**Comment by bparees** [comment]
> Ah, then they won't be part of fresh installs. That's good.

to be fair i haven't looked, but that would be my expectation if they've been removed.  Here's what the samples operator currently installs:

https://github.com/openshift/cluster-samples-operator/tree/master/assets/operator/ocp-x86_64

i don't see a `dotnet/templates` dir there, so i expect they've been removed.
