### ISSUE TITLE
The Data Virtualization image stream has unresolvable version

### ISSUE THREAD

**Issue by mechevarria** [openshift/library#34]
https://github.com/openshift/library/blob/master/official/datavirt/imagestreams/jboss-datavirt63-openshift-rhel7.json

Version 1.0 is not resolvable.  The current version that is available is 1.2

**Comment by bparees** [comment]
that value is coming from here: https://github.com/jboss-openshift/application-templates/blob/master/jboss-image-streams.json#L644-L651

So if it's not valid anymore, that file needs to be updated.  @rcernich ?

**Comment by bparees** [comment]
@mechevarria `registry.access.redhat.com/jboss-datavirt-6/datavirt63-openshift:1.0` still exists, so the imagestream is not incorrect (though I am updating the imagestream to include the 1.1 and 1.2 tags in response to your other issue).  When you say it's not resolveable, what issue are you seeing?

**Comment by rcernich** [comment]
I'm not sure what the issue is, exactly.  There was an issue reported in application-templates about this: https://github.com/openshift/library/blob/master/official/datavirt/templates/datavirt63-basic-s2i.json#L109 and it looks like the latest tag is 1.1.  However, the 1.0 tag exists in the registry and appears up-to-date.  I'll create a JIRA on our end to update our templates, so it's pointing to the latest tag.  Other than that, I don't see why the current version wouldn't work.

That said, these are injected via our extension mechanism, so it may be that the 3.6 issue affecting directory permissions on mounts from ImageSources is causing the modules to not be installed properly coming out of s2i.  I don't know.

**Comment by mechevarria** [comment]
Attempting to pull the build results in an error saying that cannot find latest tagged image.  In looking at the versions 1.0 has a label of 'unavailable' in Openshift, but 1.1 and 1.2 are available

**Comment by rcernich** [comment]
for which image?

**Comment by bparees** [comment]
@mechevarria can you share the imagestream in question on your cluster?  (`oc get is jboss-datavirt63-openshift -o yaml`)

**Comment by mechevarria** [comment]
The image stream was just updated with the newer version a couple hours.  Before since only 1.0 was listed you got an error.  Screenshot shows the issues

![error](https://user-images.githubusercontent.com/2657771/29326514-d1f39af8-81b9-11e7-8816-06058dca1da6.png)

**Comment by bparees** [comment]
the changes I made should not have affected the availability of the 1.0 imagestreamtag in the imagestream.

but if your conclusion is that the state of the content is now correct/working for you, then i guess we can close this.

**Comment by mechevarria** [comment]
The 1.0 imagestreamtag was always missing.  My wording was funky.  The unavailability of the 1.0 imagestreamtag was affecting the templates that referenced that tag.  But thats a separate issue

**Comment by mechevarria** [comment]
Unfortunately pulling in the latest templates from jboss also brings in another issue

https://github.com/jboss-openshift/application-templates/issues/328

Same type of issue with a missing imagestreamtag.  This time for datagrid client 1.0

**Comment by mechevarria** [comment]
If affects all the datavirt templates

https://github.com/openshift/library/tree/master/official/datavirt/templates

**Comment by bparees** [comment]
sorry I missed adding the newly introduced files when i updated to the new xpaas level, the new imagestreams are added here:
https://github.com/openshift/library/pull/37

**Comment by mechevarria** [comment]
This issue is resolved.  The template issue with datagrid client is separate
