### ISSUE TITLE
The Data Virtualization templates reference an unresolvable version

### ISSUE THREAD

**Issue by mechevarria** [openshift/library#35]
The templates reference version 1.0.  1.0 cannot be resolved.  Current version is 1.2.

https://github.com/openshift/library/tree/master/official/datavirt/templates

**Comment by bparees** [comment]
looks like the newest content references 1.2 here:
https://github.com/jboss-openshift/application-templates/blob/ose-v1.4.5/datavirt/datavirt63-basic-s2i.json#L265

so we can update what we're importing to that.  @rcernich in the future you might consider submitting a PR to this repo when cutting new xpaas imagestreams/templates:

https://github.com/openshift/library/blob/master/official.yaml#L2
