### ISSUE TITLE
Add Jaeger template/s

### ISSUE THREAD

**Issue by pavolloffay** [openshift/library#54]
Hi,

we would like to add Jaeger https://github.com/jaegertracing/jaeger-openshift templates into this repository to make it easier for people to use it. 

There are two types of templates: 
* all-in-one with in-memory storage
* production which requires Cassandra or Elasticsearch. The problem might be that there is no ES/C* template in this repository which could be re-used. Is there an interest in having a generic ES template?

What are the requirements to add a template to this project? Are there any special support requirements?

**Comment by bparees** [comment]
> What are the requirements to add a template to this project? Are there any special support requirements?

As long as you put it in community.yaml (not official.yaml) there are no support requirements, just make a pull adding your template and we'll review it to make sure it looks "sane".

> production which requires Cassandra or Elasticsearch. The problem might be that there is no ES/C* template in this repository which could be re-used. Is there an interest in having a generic ES template?

No objections here...  not sure if @jcantrill might have an opinion.  At a minimum he'd probably be the best person to review any template being submitted.

**Comment by pavolloffay** [comment]
@bparees thanks, I have some more questions:

Do you run any CI for community templates? 
How can we get Jaeger to official templates? What are the requirements?

**Comment by bparees** [comment]
> Do you run any CI for community templates?

not currently, no.

> How can we get Jaeger to official templates? What are the requirements?

I think you'd need to work with the business side for that.  Probably both your PM and someone from the openshift side like @sspeiche.  But at a minimum your template would need to be based on a rhel image that is shipped in registry.access.redhat.com and fully supported.

**Comment by sspeiche** [comment]
+1 to adding it here

**Comment by bparees** [comment]
@pavolloffay closing this issue but you're welcome to make the PR adding the content.

**Comment by pavolloffay** [comment]
We are decided no to add Jaeger here at the moment for the following reasons:
* these templates are not pulled minishift, oc 
* there is no CI
* there is no website/marketing

For now we keep jaeger templates in https://github.com/jaegertracing/jaeger-openshift
