### ISSUE TITLE
Update wildfly imagestreams with 11 and 12

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/library#62]
Wildfly 11 and 12 are already released and are not here:
https://github.com/openshift/library/blob/master/community/wildfly/imagestreams/wildfly-centos7.json

**Comment by bparees** [comment]
will be fixed when this PR goes through. it's blocked by other things.
https://github.com/openshift/library/pull/59/files#diff-423f8449a3d5581e340f7593bf7ecfcfR29
