### ISSUE TITLE
Rename index.md to readme.md

### ISSUE THREAD

**Issue by luciddreamz** [openshift/library#7]
Currently, the rendered content of the index.md pages does not show up in the community/official directory view. We probably need to rename this to readme.md so they show up in the directory view.

https://github.com/openshift/library/blob/master/community/
https://github.com/openshift/library/blob/master/official/

**Comment by coreydaley** [comment]
That change is in my other pull request that needs review still. @bparees

**Comment by coreydaley** [comment]
Closing as will be fixed by pull request #6

**Comment by bparees** [comment]
@coreydaley just update your PR with "fixes #7" and this will get closed when your PR merges.
