### ISSUE TITLE
NodeJS 4 EOL Approaching 

### ISSUE THREAD

**Issue by jasinner** [openshift/library#71]
NodeJS 4 support in RHSCL will get to the end of life for support at the end of April. We should remove NodeJS 4 from the image streams for the official NodeJS image streams and templates.

See https://access.redhat.com/support/policy/updates/rhscl
Note: Put 'nodejs' in the search box to see nodejs supported version life cycles.

**Comment by bparees** [comment]
nodejs:4 is already marked hidden, which is our way of deprecating it:
https://github.com/openshift/library/blob/master/official/nodejs/imagestreams/nodejs-rhel7.json#L59

we do not remove tags ever because doing so would break users who have references to them.
