### ISSUE TITLE
Bucharest Gold image stream changed locations?

### ISSUE THREAD

**Issue by coreydaley** [openshift/library#81]
https://ci.openshift.redhat.com/jenkins/job/update_openshift_library/513/console

**Comment by coreydaley** [comment]
@bparees @lance 
Looks like the Bucharest Gold image stream changed locations again.
@lance Would you please submit a pull request to the library to correct the location?

Looks like this is the commit that broke us: https://github.com/bucharest-gold/centos7-s2i-nodejs/commit/b460ea31c43cd8a90302009c806fe915276902d8

**Comment by bparees** [comment]
yeah i already fixed this.

hence https://ci.openshift.redhat.com/jenkins/job/update_openshift_library/514/

**Comment by lance** [comment]
You guys are on it. Thanks!
